### ISSUE TITLE
matplotlib strange sanity check fail

### ISSUE THREAD

**Issue by sylmarien** [hpcugent/easybuild-easyconfigs#1414]
Hello,

I'm encountering a strange problem when trying to build matplotlib-1.3.0-ictce-5.3.0-Python-2.7.5. Strange because the problem appears or not depending on when I try to install this software (I'm installing a lot of software at once, matplotlib is supposed to be installed around the middle of the list. But this version fails at that point but when I try to install it at the end, when everything else is installed, it then works without any problem).

The problem occurs at the sanity check step, as you can see on the logs in this [gist](https://gist.github.com/sylmarien/d9a5195a193b4fc9662c).

Note that I also install matplotlib-1.3.1-goolf-1.4.10-Python-2.7.6 right before and this one works without any problem.

So any idea where it could come from ? (I can give you the list of software we're installing and in which order we install them if you need it)

**Comment by boegel** [comment]
@sylmarien: I just noticed this remained unanswered, my apologies...

I have been looking into issues when different toolchains are being used in the same session, see https://github.com/hpcugent/easybuild-framework/pull/1294, maybe that's related.

This bit looks scary:

```
removing '/mnt/nfs/users/homedirs/mschmitt/.local/lib/python2.7/site-packages/matplotlib-1.3.0-py2.7-linux-x86_64.egg' (and everything under it)
creating /mnt/nfs/users/homedirs/mschmitt/.local/lib/python2.7/site-packages/matplotlib-1.3.0-py2.7-linux-x86_64.egg
Extracting matplotlib-1.3.0-py2.7-linux-x86_64.egg to /mnt/nfs/users/homedirs/mschmitt/.local/lib/python2.7/site-packages
Removing matplotlib 1.3.1 from easy-install.pth file
Adding matplotlib 1.3.0 to easy-install.pth file
```

This may also be fixed by making `PythonPackage` stricter recently, see https://github.com/hpcugent/easybuild-easyblocks/pull/577 .

If you're up for it, please see if you still have this issue with a recent version of EasyBuild.

**Comment by boegel** [comment]
@sylmarien: are you still seeing this?

**Comment by sylmarien** [comment]
@boegel I am not anymore working at the University of Luxembourg, where I saw this problem, for the moment. I do not know if this problem is still present.

**Comment by boegel** [comment]
Will close until further notice, but I expect that this has been fixed via https://github.com/hpcugent/easybuild-easyblocks/pull/577
