### ISSUE TITLE
Build dependencies cannot be hidden

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyconfigs#1883]
The following in an easyconfig will not work:
```
# zlib required, but being linked instatically, so not a runtime dep
builddependencies = [('zlib', '1.2.8')]
hiddendependencies = [('zlib', '1.2.8')]
```
This results in:
```
-bash-4.2$ eb --force --hidden ./binutils-2.25.eb 
== temporary log file in case of crash /tmp/eb-KYLZRy/easybuild-Ydxdg_.log
ERROR: Failed to process easyconfig /homeb/zam/swmanage/BINUTILS/binutils-2.25.eb: Hidden dependencies with visible module names ['Core/zlib/1.2.8'] not in list of dependencies: []
```

**Comment by boegel** [comment]
Hmm, I guess we should simply relax the requirement and also accept that hidden dependencies are included in `builddependencies`. This does complicate dumping the easyconfig though, since `hiddendependencies` need to be restored in either `dependencies` or `hiddendependencies` then. See #1354.

Maybe we can simply introduce `hiddenbuilddependencies`, but I don't like where this is going...

**Comment by boegel** [comment]
This issue should be opened in the easybuild-framework repo btw, since that's where the fix needs to happen...

**Comment by ocaisa** [comment]
Transferred to easybuild-framework

**Comment by boegel** [comment]
see https://github.com/hpcugent/easybuild-framework/issues/1368, thanks @ocaisa
