### ISSUE TITLE
How to remove the build options?

### ISSUE THREAD

**Issue by lekshmideepu** [hpcugent/easybuild-easyconfigs#2156]
I am an entry level user of easy build. I would like to remove one option (-DGC_DEFAULT_PLATFORM=\'openPBS\)  from the below build step method for the software GATE-6.2. I couldn't find this in the eb file as "build opts". 
Could someone help me with this?
eg:
[build_step method]
  running command " make -j 48  LD="$CXX -L$EBROOTICC/compiler/lib/intel64"  CC="icc" CFLAGS="-O2 -xHost -ftz -fp-speculation=safe -fp-model source -gcc" CXX="icpc" CXXFLAGS="-O2 -xHost -ftz -fp-speculation=safe -fp-model source -DGC_DEFAULT_PLATFORM=\'openPBS\' -gcc" "
  (in /dev/shm/slns005/GATE/6.2/intel-2015a/GATE-6.2)

**Comment by boegel** [comment]
@lekshmideepu: welcome to the wonderful world of EasyBuild! ;-)

The GATE easyblock (see http://easybuild.readthedocs.org/en/latest/Concepts_and_Terminology.html#easyblocks) is responsible for added the `-DDGC_DEFAULT_PLATFORM` option to the `make` command, see https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/g/gate.py#L88 .

The `default_platform` easyconfig parameter that is defined specifically for GATE is supposed to allow redefining the `openPBS` value being used, but apparently `default_platform` is not used properly, and `openPBS` is hardcoded...
I opened a pull request to fix that, see https://github.com/hpcugent/easybuild-easyblocks/pull/753.

You have two options:

* you can modify your copy of the GATE easyblock (`gate.py`) in your EasyBuild installation to change the hardcoded `openPBS` to whatever you need it set
* you can patch your copy of `gate.py` in your EasyBuild installation like I did in https://github.com/hpcugent/easybuild-easyblocks/pull/753, and add a line like `default_platform = 'your_value_here'` to the GATE easyconfig file you are using

I strongly recommend the latter, since that will keep working when you install a new EasyBuild version which includes the patched `gate.py`.

**Comment by boegel** [comment]
@lekshmideepu: if this answers your questions, please close this issue

**Comment by lekshmideepu** [comment]
@boegel : Thanks a lot for the prompt response!
