### ISSUE TITLE
FFTW shared object?

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#4466]
I'm working on an easyconfig for a binary that's linked against `libfftw3.so.3`, which isn't provided by the `FFTW` easyconfig. 

Was that deliberately excluded? Or could it be easily added?

**Comment by pescobar** [comment]
@verdurin this is something I reported some time ago. I have also hit this problem. 

It's worse if you have the FFTW rpms installed in your system because if available from your system the build will use those system libs instead of the easybuild provided FFTW libs.

I patch all my FFTW installations like this to solve this problem:

`common_configopts = "--enable-threads --enable-openmp --with-pic --enable-shared"`

IMHO, this should be the default for all the FFTW easyconfigs in easybuild.

**Comment by pescobar** [comment]
btw, I have noticed that old FFTW easyconfig were already including this option but in the newest ones the option was removed. E.g.

https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/f/FFTW/FFTW-2.1.5-GCC-4.6.3.eb#L16

**Comment by boegel** [comment]
@verdurin I don't think there's a reason we're not building the FFTW shared libraries, and it's quite straightforward to enable it, cfr. https://github.com/hpcugent/easybuild-easyblocks/pull/1180

**Comment by boegel** [comment]
fixed in https://github.com/hpcugent/easybuild-easyblocks/pull/1180, which will be included in the next release, i.e. EasyBuild v3.3.0

You will need to make sure the FFTW easyconfigs you are using are using the recently introduced FFTW easyblock (the FFTW easyconfigs included in recent EasyBuild releases do).
