### ISSUE TITLE
HDF5-1.8.18-intel2017a cannot download hdf5-1.8.18.tar.gz from anywhere

### ISSUE THREAD

**Issue by reedts** [hpcugent/easybuild-easyconfigs#4744]
Apparently `hdf5-1.8.18.tar.gz` was completely deleted from HDF5's web archive. Should it be bumped to `hdf5-1.8.19.tar.gz` which is currently available but would break any dependencies on `hdf5-1.8.18.tar.gz`?

**Comment by boegel** [comment]
Since versions older than 1.8.18 are still available, I suspect this was done by mistake (1.8.19 was released very recnently), so we should try and get them to reinstate those source tarballs...

I'll try to contact them (maybe pinging @HDFGroup suffices?).

We don't remove easyconfig files for old software, even when the source is no longer publicly available (since a lot of people have it already downloaded and thus can still install it if they want to).

**Comment by boegel** [comment]
@reedts 1.8.18 is still available, but just in a different location, see https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/src/ (figured that out via https://twitter.com/hdf5/status/875772402927624192)

So maybe we should update the alternative download URLs used by EasyBuild...

**Comment by boegel** [comment]
Fixed in #4749, thanks for reporting @reedts!
